name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        go: [ 1.16, 1.17, 1.18 ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Set up golang with version ${{ matrix.go }}
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test -v -coverprofile=covprofile ./...
      - name: Send coverage
        if: ${{ matrix.os == 'macos-latest' && matrix.go == '1.16'}}
        uses: shogo82148/actions-goveralls@4cd937b8d4bc76c0624cfe4a10469431b6718a59 # v1.4.2
        with:
          path-to-profile: covprofile